let ob=[
    {country:"Afghanistan", time: 270}, //Storing all country names and their offset values into object
    {country:"Albania", time: 60},
    {country:"Algeria", time: 60},
    {country:"Andorra", time: 60},
    {country:"Angola", time: 60},
    {country:"Antarctica", time: 180},
    {country:"Argentina", time: -180},
    {country:"Armenia", time: 240},
    {country:"Aruba", time: -240},
    {country:"Australia", time: 660},
    {country:"Austria", time: 60},
    {country:"Azerbaijan", time: 240},
    {country:"Bahamas", time: -240},
    {country:"Bahrain", time: 240},
    {country:"Bangladesh", time: 360},
    {country:"Barbados", time: -240},
    {country:"Belarus", time: 180},
    {country:"Belgium", time: 60},
    {country:"Belize", time: -180},
    {country:"Benin", time: 60},
    {country:"Bermuda", time: -240},
    {country:"Bhutan", time: 300},
    {country:"Bolivia", time: -240},
    {country:"Bosnia and Herzegovina", time: 60},
    {country:"Botswana", time: 120},
    {country:"Brazil", time: -120},
    {country:"British Indian Ocean Territory", time: 300},
    {country:"Brunei Darussalam", time: 420},
    {country:"Bulgaria", time: 120},
    {country:"Burkina Faso", time: 60},
    {country:"Burundi", time: 120},
    {country:"Cambodia", time: 420},
    {country:"Cameroon", time: 60},
    {country:"Canada", time: -240},
    {country:"Cape Verde", time: -60},
    {country:"Cayman Islands", time: -240},
    {country:"Central African Republic", time: 60},
    {country:"Chad", time: 60},
    {country:"Chile", time: -180},
    {country:"China", time: 330},
    {country:"Colombia", time: -180},
    {country:"Comoros", time: 180},
    {country:"Congo", time: 60},
    {country:"Congo, The Democratic Republic of the", time: 120},
    {country:"Cook Islands", time: 780},
    {country:"Costa Rica", time: -240},
    {country:"Cote D'Ivoire", time: 60},
    {country:"Croatia", time: 60},
    {country:"Cuba", time: -240},
    {country:"Cyprus", time: 120},
    {country:"Czech Republic", time: 60},
    {country:"Denmark", time: 60},
    {country:"Djibouti", time: 180},
    {country:"Dominica", time: 240},
    {country:"Dominican Republic", time: 240},
    {country:"Ecuador", time: 300},
    {country:"Egypt", time: 120},
    {country:"El Salvador", time: 360},
    {country:"Equatorial Guinea", time: 60},
    {country:"Eritrea", time: 180},
    {country:"Estonia", time: 120},
    {country:"Ethiopia", time: 180},
    {country:"Fiji", time: 720},
    {country:"Finland", time: 120},
    {country:"France", time: 60},
    {country:"Gabon", time: 60},
    {country:"Gambia", time: 0},
    {country:"Georgia", time: 240},
    {country:"Germany", time: 60},
    {country:"Ghana", time: 0},
    {country:"Greece", time: 120},
    {country:"Grenada", time: 240},
    {country:"Guatemala", time: 360},
    {country:"Guinea", time: 0},
    {country:"Guinea-Bissau", time: 60},
    {country:"Guyana", time: 240},
    {country:"Haiti", time: 300},
    {country:"Honduras", time: 360},
    {country:"Hungary", time: 60},
    {country:"Iceland", time: 0},
    {country:"India", time: 330},
    {country:"Indonesia", time: 420},
    {country:"Iran", time: 240},
    {country:"Iraq", time: 180},
    {country:"Ireland", time: 0},
    {country:"Israel", time: 120},
    {country:"Italy", time: 60},
    {country:"Ivory Coast", time: 0},
    {country:"Jamaica", time: 300},
    {country:"Japan", time: 540},
    {country:"Jordan", time: 120},
    {country:"Kazakhstan", time: 360},
    {country:"Kenya", time: 180},
    {country:"Kiribati", time: 780},
    {country:"Kosovo", time: 60},
    {country:"Kuwait", time: 180},
    {country:"Kyrgyzstan", time: 360},
    {country:"Laos", time: 420},
    {country:"Latvia", time: 120},
    {country:"Lebanon", time: 120},
    {country:"Lesotho", time: 120},
    {country:"Liberia", time: 0},
    {country:"Libya", time: 60},
    {country:"Liechtenstein", time: 60},
    {country:"Lithuania", time: 120},
    {country:"Luxembourg", time: 60},
    {country:"Macedonia", time: 60},
    {country:"Madagascar", time: 180},
    {country:"Malawi", time: 120},
    {country:"Malaysia", time: 480},
    {country:"Maldives", time: 300},
    {country:"Mali", time: 0},
    {country:"Malta", time: 60},
    {country:"Marshall Islands", time: 720},
    {country:"Mauritania", time: 0},
    {country:"Mauritius", time: 240},
    {country:"Mexico", time: 360},
    {country:"Micronesia", time: 720},
    {country:"Moldova", time: 120},
    {country:"Monaco", time: 60},
    {country:"Mongolia", time: 420},
    {country:"Montenegro", time: 60},
    {country:"Morocco", time: 0},
    {country:"Mozambique", time: 120},
    {country:"Myanmar", time: 390},
    {country:"Namibia", time: 120},
    {country:"Nauru", time: 720},
    {country:"Nepal", time: 345},
    {country:"Netherlands", time: 60},
    {country:"New Zealand", time: 780},
    {country:"Nicaragua", time: 360},
    {country:"Niger", time: 60},
    {country:"Nigeria", time: 60},
    {country:"North Korea", time: 540},
    {country:"Norway", time: 60},
    {country:"Oman", time: 240},
    {country:"Pakistan", time: 300},
    {country:"Palau", time: 540},
    {country:"Panama", time: 300},
    {country:"Papua New Guinea", time: 600},
    {country:"Paraguay", time: 240},
    {country:"Peru", time: 300},
    {country:"Philippines", time: 480},
    {country:"Poland", time: 60},
    {country:"Portugal", time: 0},
    {country:"Qatar", time: 240},
    {country:"Romania", time: 120},
    {country:"Russia", time: 180},
    {country:"Rwanda", time: 120},
    {country:"Saint Kitts and Nevis", time: 240},
    {country:"Saint Lucia", time: 240},
    {country:"Saint Vincent and the Grenadines", time: 240},
    {country:"Samoa", time: 660},
    {country:"San Marino", time: 60},
    {country:"Sao Tome and Principe", time: 60},
    {country:"Saudi Arabia", time: 180},
    {country:"Senegal", time: 0},
    {country:"Serbia", time: 60},
    {country:"Seychelles", time: 180},
    {country:"Sierra Leone", time: 0},
    {country:"Singapore", time: 480},
    {country:"Slovakia", time: 60},
    {country:"Slovenia", time: 60},
    {country:"Solomon Islands", time: 660},
    {country:"Somalia", time: 180},
    {country:"South Africa", time: 120},
    {country:"South Korea", time: 540},
    {country:"South Sudan", time: 180},
    {country:"Spain", time: 60},
    {country:"Sri Lanka", time: 360},
    {country:"Sudan", time: 120},
    {country:"Suriname", time: 240},
    {country:"Swaziland", time: 120},
    {country:"Sweden", time: 60},
    {country:"Switzerland", time: 60},
    {country:"Syria", time: 120},
    {country:"Taiwan", time: 480},
    {country:"Tajikistan", time: 300},
    {country:"Tanzania", time: 180},
    {country:"Thailand", time: 420},
    {country:"Timor-Leste", time: 540},
    {country:"Togo", time: 0},
    {country:"Tonga", time: 780},
    {country:"Trinidad and Tobago", time: 240},
    {country:"Tunisia", time: 60},
    {country:"Turkey", time: 120},
    {country:"Turkmenistan", time: 300},
    {country:"Tuvalu", time: 720},
    {country:"Uganda", time: 180},
    {country:"Ukraine", time: 120},
    {country:"United Arab Emirates", time: 240},
    {country:"United Kingdom", time: 0},
    {country:"United States", time: 300},
    {country:"Uruguay", time: 180},
    {country:"Uzbekistan", time: 300},
    {country:"Vanuatu", time: 660},
    {country:"Vatican City", time: 60},
    {country:"Venezuela", time: -240},
    {country:"Vietnam", time: 420},
    {country:"Yemen", time: 180},
    {country:"Zambia", time: 120},
    {country:"Zimbabwe", time: 120}
];
let select=document.getElementById("Country-Name"); // Create Option for each countries 
for (let i = 0; i < ob.length; i++) {
    let opt=document.createElement("option");
    opt.text=ob[i].country;
    opt.value=ob[i].country;
    select.add(opt);
}



let pre_country="abc",pre_time;// Store the prev country and time, so that if user don't change the country, it will not traverse the object which reduces Time complexity
function onChangeTimeZone(event){ // Detect the country name 
    let countryname=event.target.value;
    let time=0;
    if(pre_country!=countryname){// Checking whether previous country name and current country names are same or not
        for(let i=0;i<ob.length;i++){
            if(ob[i].country==countryname) {
                time=ob[i].time; // storing the offset time 
            }
        }
    }
    else{
        time=pre_time;
    }
    let temp=new Date();
    let countrytime;
    if(countryname!="india"){
        countrytime=new Date(temp.getTime()+(time*60000)-(330*60000));// Calculating the current time for respective country
    }
    else countrytime=new Date();
    document.getElementById('txt').innerHTML="The current Date and Time is "+countrytime.toLocaleString();
    pre_country=countryname;
    pre_time=time;
    setTimeout(()=>onChangeTimeZone(event),1000);// calling the onchangetimezone function by 1 sec gap so that our time get updated by each second
}